Repository kyma-project/cp-mod-migrator, pull requests merged in 2024-02, with the labels that each got.

#12 Adapt migrator application to agreed chages
  Makefile
  cmd/generators/proxy-conf-type-gen/main.go
  cp_mod_migration_suite_test.go
  cp_mod_migration_test.go
  cp_mod_migration_utilz_test.go
  hack/cproxy/crd.yaml
  hack/testdata/connectivity-proxy-operator-all.yaml
  hack/testdata/cp-test-cr.yaml
  hack/testdata/cp_default_cr.yaml
  main.go
  pkg/cluster_status.go
  pkg/cproxy/api/v211/type_http.go
  pkg/cproxy/api/v211/type_rfcandldap.go
  pkg/cproxy/api/v211/type_socks5.go
  pkg/cproxy/api/v211/types.go
  pkg/cproxy/api/v211/zz_generated.deepcopy.go
  pkg/cproxy/api/v293/types.go
  pkg/extract/get_cp_config.go
  pkg/extract/get_cp_info.go
  pkg/extract/set_cp_defaults.go
  pkg/extract/set_secret_config.go
  pkg/pkg_suite_test.go
  pkg/run.go
Labels: cla: yes, size/XXL, lgtm

#13 Backup script development
  cp_mod_migration_test.go
  hack/test-deployment/connectivity-proxy-operator-all.yaml
  hack/test-deployment/deployment.yaml
  images/backup/backup.sh
  images/cleaner/cleaner.sh
  pkg/run.go
Labels: cla: yes, lgtm, size/L

#16 Fix small problem - typo for RBAC yaml file
  hack/test-deployment/connectivity-proxy-operator-all.yaml
Labels: cla: yes, lgtm, size/XS

#19 Run backup script only after CR is migrated
  images/backup/backup.sh
Labels: cla: yes, lgtm, size/XS

#20 Connectivity Proxy Migrator Readme
  README.md
Labels: cla: yes, lgtm, size/L

#21 Add labeling of migrated resources with app.kubernetes.io/managed-by=sap.connectivity.proxy.operator
  README.md
  images/cleaner/cleaner.sh
Labels: cla: yes, lgtm, size/S

#22 Fix of the rollback script
  README.md
Labels: cla: yes, lgtm, size/S

#23 Cp monitoring script
  scripts/monitor-cp.sh
Labels: cla: yes, lgtm, size/M

#24 Use fqdn for deleting certificate resource
  images/cleaner/cleaner.sh
Labels: cla: yes, lgtm, size/XS

#25 CP monitoring script improvements
  scripts/monitor-cp.sh
Labels: cla: yes, lgtm, size/M

#26 Include removal of orphaned CP 2.7 RBAC resources
  images/cleaner/cleaner.sh
Labels: cla: yes, lgtm, size/XS
