Repository kyma-project/cp-mod-migrator, pull requests merged in 2024-01, with the labels that each got.

#1 Move code to new repo
  .github/workflows/run-tests.yaml
  .gitignore
  Dockerfile
  Makefile
  cmd/generators/proxy-conf-type-gen/main.go
  cp_mod_migration_suite_test.go
  cp_mod_migration_test.go
  cp_mod_migration_utilz_test.go
  data/schema.json
  go.mod
  go.sum
  hack/cproxy/connectivity-proxy-cm.yaml
  hack/cproxy/crd.yaml
  hack/testdata/configmaps.yaml
  hack/testdata/configmaps_test.yaml
  hack/testdata/cp_cm.yaml
  hack/testdata/cp_config_data.yaml
  hack/testdata/cp_stateful_set.yaml
  main.go
  pkg/cluster_status.go
  pkg/cluster_status_test.go
  pkg/cproxy/api/v293/types.go
  pkg/cproxy/api/v294/type_http.go
  pkg/cproxy/api/v294/type_rfcandldap.go
  pkg/cproxy/api/v294/type_socks5.go
  pkg/cproxy/api/v294/types.go
  pkg/cproxy/api/v294/zz_generated.deepcopy.go
  pkg/extract/get_cp_config.go
  pkg/extract/get_cp_config_test.go
  pkg/extract/mock_gen_test.go
  pkg/extract/mocks/Client.go
  pkg/extract/set_cp_defaults.go
  pkg/mocks/Client.go
  pkg/pkg_suite_test.go
  pkg/run.go
Labels: cla: yes, size/XXL, lgtm

#2 Add more tests
  cp_mod_migration_suite_test.go
  cp_mod_migration_test.go
  cp_mod_migration_utilz_test.go
  hack/cproxy/connectivity-proxy-cm.yaml
  hack/testdata/configmaps.yaml
  hack/testdata/configmaps_test.yaml
  hack/testdata/cp_cm.yaml
  hack/testdata/cp_cm_info.yaml
  hack/testdata/cp_config_data.yaml
  main.go
  pkg/cproxy/api/v293/types.go
  pkg/extract/get_cp_config.go
  pkg/extract/get_cp_config_test.go
  pkg/extract/get_cp_info.go
  pkg/extract/mock_gen_test.go
  pkg/run.go
Labels: cla: yes, size/XXL, lgtm

#9 Adding containers to perform Connectivity Proxy backup and cleanup
  .gitignore
  images/backup/Dockerfile
  images/backup/backup.sh
  images/cleaner/Dockerfile
  images/cleaner/cleaner.sh
  images/cleaner/deployment.yaml
  images/cleaner/rbac.yaml
Labels: cla: yes, lgtm, size/S

#8 adapt code to new requirements
  cp_mod_migration_test.go
  cp_mod_migration_utilz_test.go
  hack/cproxy/crd.yaml
  pkg/cluster_status.go
  pkg/cluster_status_test.go
  pkg/cproxy/api/v294/types.go
  pkg/cproxy/api/v294/zz_generated.deepcopy.go
  pkg/extract/set_cp_defaults.go
  pkg/pkg_suite_test.go
  pkg/run.go
Labels: cla: yes, lgtm, size/XL

#10 Implementation of the cleanup script and test deployment
  hack/test-deployment/cluster-admin-rbac.yaml
  hack/test-deployment/deployment-single.yaml
  hack/test-deployment/deployment.yaml
  images/backup/Dockerfile
  images/backup/backup.sh
  images/cleaner/Dockerfile
  images/cleaner/cleaner.sh
  images/cleaner/deployment.yaml
  images/cleaner/rbac.yaml
Labels: cla: yes, lgtm, size/L
